Template endpoint for slackbot
varianter/this-is-variant-music-api pull request #2
Opened 2021-05-20 20:41 UTC by Zindre17

2021-05-21 07:42 UTC, adriansberg approved these changes

2021-05-21 07:46 UTC, oskogstad requested changes

2021-05-21 07:46 UTC, oskogstad commented on Controllers/SlackController.cs
> +    public class SlackController : ControllerBase
Kan kanskje endre navnet her? Trenger ikke nødvendigvis å komme fra Slack 😁 RecommendationController eller no? Og dataklassen, MusicRecommendation?

2021-05-25 07:27 UTC, adriansberg commented
Denne er det sikkert bare å merge, tror du ikke det @oskogstad? 🚀

2021-06-08 18:22 UTC, merged